### ISSUE TITLE
Research Headless CMS'es

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#1]
Acceptance criteria:
- Has preview
- Has the possibility of building plugins
- Is focussed on content-editor (end user)

**Comment by deannabosschert** [comment]
http://tilda.cc/de/

**Comment by kriskuiper** [comment]
https://prismic.io/

**Comment by kriskuiper** [comment]
https://www.datocms.com/ Hier heb ik zelf al wat ervaring mee, is niet echt lekker als je iets van een page builder zou willen maken maar wel okay en heeft een GraphQL api 😏

**Comment by kriskuiper** [comment]
https://www.storyblok.com/ Hier gaat zwaar m'n voorkeur naar uit

**Comment by kriskuiper** [comment]
https://v5.keystonejs.com/

**Comment by gijslaarman** [comment]
https://wordpress.org/

**Comment by kriskuiper** [comment]
> https://wordpress.org/ Goedkoop, headless, super chil voor posts te schrijven (veel mensen. Kan geen pages builden (misschien een plugin wel).

Pages builden is niet iets wat het CMS precies doet. Je kan in een headless oplossing ook kiezen om prebuild alle data uit de WP api te halen en dan zo te gebruiken in je templates etc.
