### ISSUE TITLE
Break open the grid layout

### ISSUE THREAD

**Issue by gijslaarman** [kriskuiper/cmd-digital-playground#107]
## Description
Currently the hero-header component is contained in the main of each page, but it should be fluid and full page width. 
How are we going to fix this? 

Can we make a system where it's possible to create components that are 100% wide.

## Acceptance criteria
- [ ] Components can be 100% wide.

**Comment by kriskuiper** [comment]
I think we just have to let the modular-content be 100% wide, as every component in it, and then style the components seperately

**Comment by kriskuiper** [comment]
Because right now the `main` for example is 1080px wide at max, that should not be the case
