### ISSUE TITLE
Make preview less buggy

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#135]
## Description
Try to fix the preview so we don't get a 404 when creating a page. Maybe we can render our own page on 404 and check if env === dev || production and then render a fallback 404 page with something like 'Your page is building... please wait a sec'.

## Acceptance criteria
- [ ] 404 does render a fallback page instead of Vercel 404
- [ ] Maybe check for environment and give subsequent feedback

**Comment by deannabosschert** [comment]
https://www.storyblok.com/apps/advanced-paths

**Comment by deannabosschert** [comment]
Tbh if it's too complex, I'd just ask in the Storyblok Discord if anyone has any suggestions.
