### ISSUE TITLE
Write docs for specific user journeys

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#137]
## Description
The user journeys should be written out in the project wiki so we can validate that we understand how every persona is walking through the CMS. (Adding components, creating pages etc.)

## Acceptance criteria
- [x] Info is in Wiki

**Comment by deannabosschert** [comment]
Already written those in Dropbox Paper a while ago as User Stories, will convert those to actual CJP's which can be used as a user manual as well
