### ISSUE TITLE
Make plan for user testing with Mattijs

### ISSUE THREAD

**Issue by deannabosschert** [kriskuiper/cmd-digital-playground#148]
## Description
At 13:00 pm we've planned a user test with Mattijs (the client).
What's the plan?

## Acceptance criteria
- [x] Decide what path we want to test
- [x] Write down the 'expected' path (try it yourself)
- [x] Find a way to get Mattijs to log in(?)
- [x] Decide on the remote meeting tool

**Comment by deannabosschert** [comment]
Test path: create new event in Storyblok

**Comment by kriskuiper** [comment]
Maybe we should let him create a new Golden Dot Awards page, you know, somewhat more specific?

**Comment by deannabosschert** [comment]
I'll let him create the current Golden Dot Awards page then!
