### ISSUE TITLE
Make live preview work in a nicer way

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#17]
## Description
Right now we hijack the modular content with JS when it opens in Storyblok so we can live update the preview. This is definitely not an ideal situation and so we have to find a better solution to this.

## Acceptance criteria
- Preferably run a new build or something on change and when the site is in the editor's context
- Make it easily accessible to new (unexperienced) developers

**Comment by gijslaarman** [comment]
Would be nice to handle the preview changes with the build in render function on nunjucks: https://mozilla.github.io/nunjucks/getting-started.html#when-in-the-browser. Link the components in the `/src/**/components` to the preview website.

**Comment by kriskuiper** [comment]
Maybe we could leverage something like localStorage to dump the newly created HTML in like a string? Brainstormed some with Janno.

**Comment by kriskuiper** [comment]
Other solution could be to deploy a node instance of the same project somewhere else but that would be cumbersome since we then need to update two repo's at once.

**Comment by kriskuiper** [comment]
We could do the following things:
- Strip out the sandbox and forget preview all along, so then there's no preview website to worry about
- Trigger preview deploy from a task in Storyblok (user needs to go back, click trigger preview deploy and go back to the page 🤦 )

**Comment by kriskuiper** [comment]
Going for the second option and closing this issue to work on the solution in another issue
