### ISSUE TITLE
Let Nunjucks handle the template generation.

### ISSUE THREAD

**Issue by gijslaarman** [kriskuiper/cmd-digital-playground#21]
https://github.com/kriskuiper/cmd-digital-playground/blob/0033c8cca63d1507bead2b619f1d44b100543e96/src/assets/js/preview-environment/components/test-component.js#L12

Can we change the template literal by a nunjucks.render() function?

**Comment by kriskuiper** [comment]
Will handle this as follow up to the review of @gijslaarman in #16
