### ISSUE TITLE
Implement component-based scss

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#25]
## Description
Right now we only can use scss from `src/assets/scss` but ideally we want to let a component have it's own .scss file and then use `node-sass` glob thingies to build everything from `src/components/**/*.scss` to a css file.

## Acceptance criteria
- Every component can have it's own scss file
- Everything gets bundled into one css file
- Works when running a build
- Works when running `npm run dev` so when live server is running etc.

**Comment by gijslaarman** [comment]
Done 🎉
