### ISSUE TITLE
Decide on what content should go into event page

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#55]
## Description
We now know that we want to focus on building event pages. But what we don't know is what types of content should go into that page, so we have to investigate that. We also could look into what could go onto the main events page and do something with that besides obviously showing some events.

## Acceptance criteria
- Make a decision on what goes into that page
- Document the what and why

**Comment by gijslaarman** [comment]
@deannabosschert How's this going? Need me to pick it up?

**Comment by deannabosschert** [comment]
It's going well! Had an interruption because of a medical call but you may expect it in +- an hour :)

**Comment by deannabosschert** [comment]
- [Documented in Dropbox paper](https://paper.dropbox.com/doc/Eventspage-componenten--A1MHaKCCM_vKcCZ1SEAhhSMfAg-e1w1br1yhMLkFQ2HqgPMt).


- [Research beforehand](https://paper.dropbox.com/doc/Events-iROithbX4uRW0pqF1JfJp)
