### ISSUE TITLE
Create new component: next 3 events.

### ISSUE THREAD

**Issue by gijslaarman** [kriskuiper/cmd-digital-playground#58]
## Description
Create a new component that can be reused on the website to show the next upcoming 3 events.

## Acceptance criteria
- [x] Create 'Latest three events' component in Storyblok
- [x] Content is empty in Storyblok but based on data (will be assigned by our script so its data is relative to the single events)
- [x] Latest three events component has `event-component` as child.

Tickets #55 & #56 should go first

![100%](https://progress-bar.dev/100)

**Comment by kriskuiper** [comment]
Blocked by #61

**Comment by deannabosschert** [comment]
Ticket is done, but can't be tested yet due to two bugs stated in other Issues.

**Comment by kriskuiper** [comment]
Blocked by #85 and #87
