### ISSUE TITLE
Add all data to event content type

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#61]
## Description
Every event now only has a title. Ofcourse it needs other fields that @deannabosschert found in #55.

## Acceptance criteria
- [x] All needed fields are in the content type
- [x] Implementation all around

**Comment by deannabosschert** [comment]
I'll pick up the 'implementation all around' part!

**Comment by kriskuiper** [comment]
That's just adding the data to site/events right?

**Comment by deannabosschert** [comment]
As far as I know; yes.

**Comment by deannabosschert** [comment]
Checked and 💯
