### ISSUE TITLE
Real path in CMS is not caching the links correctly

### ISSUE THREAD

**Issue by gijslaarman** [kriskuiper/cmd-digital-playground#65]
## Description
The cached urls that are fetched on build for the main menu header don't work as intended. Only Henk is done right. Currently the links are as followed:
```
<a href="demo">DEMO</a>
<a href="/henk">HENK</a>
<a href="home">HOME</a>
```

The href should be /demo or /home like /henk, so that it will look for the demo folder in the root folder not the folder it currently is in. If you were to be in http://localhost:3000/home and click on the demo link it will direct you to http://localhost:3000/home/demo instead of http://localhost:3000/demo.

## Acceptance criteria
hrefs in the main menu are directed to the root folder or the path chosen in real path.

**Comment by kriskuiper** [comment]
Right, so we have to prefix every slug with /in the header? Or every slug in general?

**Comment by gijslaarman** [comment]
Also added in an extra fallback: https://www.11ty.dev/docs/filters/url/ to the header. Maybe make a link component later? @kriskuiper @deannabosschert
