### ISSUE TITLE
Presentation/demo for client

### ISSUE THREAD

**Issue by deannabosschert** [kriskuiper/cmd-digital-playground#70]
## Description
Prepare a Google Presentation for the meeting with our client this Friday.

## Acceptance criteria
- [x] Recap assignment
- [x] Recap last time ('voeg een recap toe!')
- [x] Customer Journey (for the client + stakeholders)
- [x] What we have done this sprint
- [x] What we will do next sprint
- [x] Questions

**Comment by kriskuiper** [comment]
Gaan we hier full on CMD style?

**Comment by deannabosschert** [comment]
Zeker wel.

**Comment by deannabosschert** [comment]
https://docs.google.com/presentation/d/1kSCS1ofZv0Q-ZrjTsbYmqDfg6ZvUW5n5LrO3-OE8fWU/edit?usp=sharing
