### ISSUE TITLE
Event component

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#71]
## Description
An event should look like an event card, make it look like that.

## Acceptance criteria
- [x] Search for voorbeelden
- [x] Looks like an event card
- [x] Events on events index page are cards.

**Comment by kriskuiper** [comment]
Some resources for inspiration:
- https://www.eventbrite.nl/
- https://wwww.meetup.com/nl-NL/
- https://hike.one/updates < Hier gaat m'n voorkeur wel naar uit omdat het minder mainstream is en qua design best dicht bij CMD kan liggen

**Comment by gijslaarman** [comment]
Reopening for styling criteria

**Comment by kriskuiper** [comment]
Blocked by #61
