### ISSUE TITLE
Make preview branch update on save

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#88]
## Description
We can use our earlier implementation with the Storyblok SDK but instead of hijacking the page with JS, we can just do a fetch to the preview-branch Vercel webhook.

## Acceptance criteria
- [x] Use [Storyblok bridge](https://www.storyblok.com/docs/Guides/storyblok-latest-js)
- [x] Preview branch gets updated on save and created
- [x] Master branch gets updated on publish or unpublish

**Comment by deannabosschert** [comment]
Maybe check out the paid plans; I remember the availability of an app/plugin in the trial period that can automate this.
