### ISSUE TITLE
Add cool styles and components

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#90]
## Description
We're CMD, the website should look like we're CMD students. Just awesome. Also we should add some more components.

## Acceptance criteria
- [ ] Look at cool websites for types of animations and micro-animations
- [x] Look at what components are needed now
- [ ] Impelement design
- [ ] Implement new components

![25%](https://progress-bar.dev/25)

**Comment by deannabosschert** [comment]
@kriskuiper wat is exact de definition of done hier?
