### ISSUE TITLE
Remove other stupid pages

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#97]
## Description
All dummy content for pages has to be removed

## Acceptance criteria
- [x] No 'My page'
- [x] No 'Henk'
- [x] No 'Demo page'
- [x] Home is bound to / in Storyblok and in the front-end (do something with real path etc.)

**Comment by kriskuiper** [comment]
Since I'm already busy with the home page, I'll fix it in the front-end

**Comment by gijslaarman** [comment]
Oh great!

**Comment by kriskuiper** [comment]
@gijslaarman Can you create an issue where we fix all nested CSS styling, it's giving some headaches, mainly because I just wanted to add an container to the header so the content stays within boundaries instead of being 100% width or something.

But because we use nested CSS selectors like `&__top` etc. all layout breaks... That's not what BEM should be about.

**Comment by gijslaarman** [comment]
In the SCSS it's nested, in the css output `&__top` is the same as `.parent-element__top`. Will discuss this later

**Comment by kriskuiper** [comment]
Doesn't seem to work as intended then anyway 🤷‍♂️ . We'll take a look indeed
