### ISSUE TITLE
Base design events detail page

### ISSUE THREAD

**Issue by kriskuiper** [kriskuiper/cmd-digital-playground#99]
## Description
The events detail page base design could be a lot better. It now is ugly 🤢 . From there we can design/build two more advanced cases.

## Acceptance criteria
- [x] Design looks a lot better
- [x] Look at cool websites for inspiration
- [x] Add modular-content to event detail page for later uitbreiding
- [x] Use BEM

![100%](https://progress-bar.dev/100)

**Comment by deannabosschert** [comment]
Research: https://paper.dropbox.com/doc/Events-layout--A1d1jqNc1cS7pvPv6IVcMV~uAg-HKDzpsKIZP93VSpgAGUE2

**Comment by deannabosschert** [comment]
https://codepen.io/deannabosschert/pen/xxZZdZQ
